CREATE TABLE finishedgames (
id INTEGER,
name TEXT,
genre TEXT,
release INTEGER,
platform TEXT
);

INSERT INTO finishedgames VALUES 
(1, "Project IGI", "Tactical Shooter", 2000, "PC"),
(2, "IGI 2 Covert Strike", "Tactical Shooter", 2003, "PC"),
(3, "Far Cry", "Tactical Shooter", 2004, "PC"),
(4, "Far Cry 2", "Tactical Shooter", 2008, "PC"),
(5, "Far Cry 3", "Tactical Shooter", 2012, "PC"),
(5, "Beyond Enemy Lines", "Tactical Shooter", 2017, "PC"),
(6, "Conflict Desert Storm 2", "Tactical Shooter", 2003, "PC"),
(7, "Marine Heavy Gunner Vietnam", "Tactical Shotoer", 2004, "PC"),
(8, "Ghost Recon", "Tactical Shotoer", 2001, "PC"),
(8, "Ghost Recon", "Tactical Shotoer", 2002, "PC"),
(9, "Ghost Recon", "Tactical Shotoer", 2002, "PC"),
(10, "Army Men RTS", "Real-Time Strategy", 2002, "PC"),
(11, "Dune 2000", "Real-Time Strategy", 1998, "PC"),
(12, "HAWX", "Flight Simulation", 2009, "PC"),
(13, "Need For Speed SE", "Racing Simulation", 1997, "PC"),
(14, "Need For Speed Underground 2", "Racing Simulation", 2004, "PC"),
(15, "Street Fighter X Tekken", "Fighting Simulation", 2012, "PC"),
(16, "Doom", "First Person Shooter", 1993, "PC"),
(17, "Doom 2", "First Person Shooter", 2, "PC"),
(18, "Quake 3 Arena", "First Person Shooter", 2, "PC"),
(19, "Serious Sam The First Encounter", "First Person Shooter", 2001, "PC"),
(20, "Serious Sam The Second Encounter", "First Person Shooter", 2, "PC"),
(21, "Serious Sam 2", "First Person Shooter", 2, "PC"),
(22, "Duke Nukem Manhattan Project", "Third Person Shooter", 2002, "PC"),
(23, "Bioshock", "First Person Shooter", 2, "PC"),
(24, "Medal of Honor Allied Assault", "First Person Shooter", 2002, "PC"),
(25, "Medal of Honor Allied Assault Spearhead", "First Person Shooter", 2002, "PC"),
(26, "Medal of Honor Allied Assault Breakthrough", "First Person Shooter", 2003, "PC"),
(27, "Medal of Honor", "First Person Shooter", 2010, "PC"),
(28, "Call of Duty", "First Person Shooter", 2003, "PC"),
(29, "Call of Duty 2", "First Person Shooter", 2005, "PC"),
(30, "Call of Duty 4 Modern Warfare", "First Person Shooter", 2007, "PC"),
(31, "Call of Duty Modern Warfare 2", "First Person Shooter", 2009, "PC"),
(32, "Call of Duty Black Ops", "First Person Shooter", 2010, "PC"),
(33, "Call of Duty Modern Warfare 3", "First Person Shooter", 2011, "PC"),
(34, "Call of Duty Modern Warfare 3", "First Person Shooter", 2011, "PC"),
(35, "Battlefield 1942", "First Person Shooter", 2002, "PC"),
(36, "Battlefield 2", "First Person Shooter", 2005, "PC"),
(37, "Battlefield Bad Company 2", "First Person Shooter", 2010, "PC"),
(38, "Battlefield 3", "First Person Shooter", 2011, "PC"),
(39, "Return to the Castle Wolfenstein", "First Person Shooter", 2011, "PC"),
(40, "Battlefield 3", "First Person Shooter", 2011, "PC"),
(41, "Splinter Cell Flash Game", "Stealth Action", NULL, "Online"),
(42, "Splinter Cell", "Stealth Action", 2002, "PC"),
(43, "Splinter Cell Pandora Tomorrow", "Stealth Action", 2004, "PC"),
(44, "Splinter Cell Chaos Theory", "Stealth Action", 2005, "PC"),
(45, "Splinter Cell Double Agent", "Stealth Action", 2006, "PC"),
(46, "Splinter Cell Conviction", "Stealth Action", 2010, "PC"),
(47, "Splinter Cell Blacklist", "Stealth Action", 2013, "PC"),
(48, "Splinter Cell Pandora Tomorrow", "Stealth Action", NULL, "Mobile Phone"),
(49, "Splinter Cell Chaos Theory", "Stealth Action", NULL, "Mobile Phone"),
(49, "Splinter Cell Double Agent", "Stealth Action", NULL, "Mobile Phone"),
(50, "Splinter Cell Conviction", "Stealth Action", NULL, "Mobile Phone"),
(51, "Hitman 2", "Stealth Action", NULL, "PC"),
(52, "Hitman Contracts", "Stealth Action", NULL, "PC"),
(53, "Hitman Blood Money", "Stealth Action", 2006, "PC"),
(54, "Hitman Sniper Challenge", "Stealth Action", NULL, "PC"),
(55, "Hitman Absolution", "Stealth Action", NULL, "PC"),
(56, "Metal Gear Solid Ground Zeroes", "Stealth Action", NULL, "PC"),
(57, "The Saboteur", "Stealth Action", 2009, "PC"),
(58, "Assassins Creed Brotherhood", "Action Advanture", 2010, "PC")

;


SELECT * FROM finishedgames;
